# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /nix/store/q1nssraba326p2kp6627hldd2bhg254c-cmake-3.29.2/bin/cmake

# The command to remove a file.
RM = /nix/store/q1nssraba326p2kp6627hldd2bhg254c-cmake-3.29.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/runner/workspace

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/runner/workspace

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/nix/store/q1nssraba326p2kp6627hldd2bhg254c-cmake-3.29.2/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/nix/store/q1nssraba326p2kp6627hldd2bhg254c-cmake-3.29.2/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/nix/store/q1nssraba326p2kp6627hldd2bhg254c-cmake-3.29.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/nix/store/q1nssraba326p2kp6627hldd2bhg254c-cmake-3.29.2/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/nix/store/q1nssraba326p2kp6627hldd2bhg254c-cmake-3.29.2/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/nix/store/q1nssraba326p2kp6627hldd2bhg254c-cmake-3.29.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/nix/store/q1nssraba326p2kp6627hldd2bhg254c-cmake-3.29.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/nix/store/q1nssraba326p2kp6627hldd2bhg254c-cmake-3.29.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/nix/store/q1nssraba326p2kp6627hldd2bhg254c-cmake-3.29.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/workspace/CMakeFiles /home/runner/workspace//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/workspace/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named poker_core

# Build rule for target.
poker_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 poker_core
.PHONY : poker_core

# fast build rule for target.
poker_core/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poker_core.dir/build.make CMakeFiles/poker_core.dir/build
.PHONY : poker_core/fast

#=============================================================================
# Target rules for targets named poker_core_python

# Build rule for target.
poker_core_python: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 poker_core_python
.PHONY : poker_core_python

# fast build rule for target.
poker_core_python/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poker_core_python.dir/build.make CMakeFiles/poker_core_python.dir/build
.PHONY : poker_core_python/fast

#=============================================================================
# Target rules for targets named test_card

# Build rule for target.
test_card: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_card
.PHONY : test_card

# fast build rule for target.
test_card/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_card.dir/build.make CMakeFiles/test_card.dir/build
.PHONY : test_card/fast

#=============================================================================
# Target rules for targets named test_game

# Build rule for target.
test_game: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_game
.PHONY : test_game

# fast build rule for target.
test_game/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_game.dir/build.make CMakeFiles/test_game.dir/build
.PHONY : test_game/fast

#=============================================================================
# Target rules for targets named test_hand_evaluator

# Build rule for target.
test_hand_evaluator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_hand_evaluator
.PHONY : test_hand_evaluator

# fast build rule for target.
test_hand_evaluator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_hand_evaluator.dir/build.make CMakeFiles/test_hand_evaluator.dir/build
.PHONY : test_hand_evaluator/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

python/poker_module.o: python/poker_module.cpp.o
.PHONY : python/poker_module.o

# target to build an object file
python/poker_module.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poker_core_python.dir/build.make CMakeFiles/poker_core_python.dir/python/poker_module.cpp.o
.PHONY : python/poker_module.cpp.o

python/poker_module.i: python/poker_module.cpp.i
.PHONY : python/poker_module.i

# target to preprocess a source file
python/poker_module.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poker_core_python.dir/build.make CMakeFiles/poker_core_python.dir/python/poker_module.cpp.i
.PHONY : python/poker_module.cpp.i

python/poker_module.s: python/poker_module.cpp.s
.PHONY : python/poker_module.s

# target to generate assembly for a file
python/poker_module.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poker_core_python.dir/build.make CMakeFiles/poker_core_python.dir/python/poker_module.cpp.s
.PHONY : python/poker_module.cpp.s

src/action.o: src/action.cpp.o
.PHONY : src/action.o

# target to build an object file
src/action.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poker_core.dir/build.make CMakeFiles/poker_core.dir/src/action.cpp.o
.PHONY : src/action.cpp.o

src/action.i: src/action.cpp.i
.PHONY : src/action.i

# target to preprocess a source file
src/action.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poker_core.dir/build.make CMakeFiles/poker_core.dir/src/action.cpp.i
.PHONY : src/action.cpp.i

src/action.s: src/action.cpp.s
.PHONY : src/action.s

# target to generate assembly for a file
src/action.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poker_core.dir/build.make CMakeFiles/poker_core.dir/src/action.cpp.s
.PHONY : src/action.cpp.s

src/card.o: src/card.cpp.o
.PHONY : src/card.o

# target to build an object file
src/card.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poker_core.dir/build.make CMakeFiles/poker_core.dir/src/card.cpp.o
.PHONY : src/card.cpp.o

src/card.i: src/card.cpp.i
.PHONY : src/card.i

# target to preprocess a source file
src/card.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poker_core.dir/build.make CMakeFiles/poker_core.dir/src/card.cpp.i
.PHONY : src/card.cpp.i

src/card.s: src/card.cpp.s
.PHONY : src/card.s

# target to generate assembly for a file
src/card.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poker_core.dir/build.make CMakeFiles/poker_core.dir/src/card.cpp.s
.PHONY : src/card.cpp.s

src/deck.o: src/deck.cpp.o
.PHONY : src/deck.o

# target to build an object file
src/deck.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poker_core.dir/build.make CMakeFiles/poker_core.dir/src/deck.cpp.o
.PHONY : src/deck.cpp.o

src/deck.i: src/deck.cpp.i
.PHONY : src/deck.i

# target to preprocess a source file
src/deck.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poker_core.dir/build.make CMakeFiles/poker_core.dir/src/deck.cpp.i
.PHONY : src/deck.cpp.i

src/deck.s: src/deck.cpp.s
.PHONY : src/deck.s

# target to generate assembly for a file
src/deck.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poker_core.dir/build.make CMakeFiles/poker_core.dir/src/deck.cpp.s
.PHONY : src/deck.cpp.s

src/game_state.o: src/game_state.cpp.o
.PHONY : src/game_state.o

# target to build an object file
src/game_state.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poker_core.dir/build.make CMakeFiles/poker_core.dir/src/game_state.cpp.o
.PHONY : src/game_state.cpp.o

src/game_state.i: src/game_state.cpp.i
.PHONY : src/game_state.i

# target to preprocess a source file
src/game_state.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poker_core.dir/build.make CMakeFiles/poker_core.dir/src/game_state.cpp.i
.PHONY : src/game_state.cpp.i

src/game_state.s: src/game_state.cpp.s
.PHONY : src/game_state.s

# target to generate assembly for a file
src/game_state.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poker_core.dir/build.make CMakeFiles/poker_core.dir/src/game_state.cpp.s
.PHONY : src/game_state.cpp.s

src/hand_evaluator.o: src/hand_evaluator.cpp.o
.PHONY : src/hand_evaluator.o

# target to build an object file
src/hand_evaluator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poker_core.dir/build.make CMakeFiles/poker_core.dir/src/hand_evaluator.cpp.o
.PHONY : src/hand_evaluator.cpp.o

src/hand_evaluator.i: src/hand_evaluator.cpp.i
.PHONY : src/hand_evaluator.i

# target to preprocess a source file
src/hand_evaluator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poker_core.dir/build.make CMakeFiles/poker_core.dir/src/hand_evaluator.cpp.i
.PHONY : src/hand_evaluator.cpp.i

src/hand_evaluator.s: src/hand_evaluator.cpp.s
.PHONY : src/hand_evaluator.s

# target to generate assembly for a file
src/hand_evaluator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poker_core.dir/build.make CMakeFiles/poker_core.dir/src/hand_evaluator.cpp.s
.PHONY : src/hand_evaluator.cpp.s

src/player.o: src/player.cpp.o
.PHONY : src/player.o

# target to build an object file
src/player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poker_core.dir/build.make CMakeFiles/poker_core.dir/src/player.cpp.o
.PHONY : src/player.cpp.o

src/player.i: src/player.cpp.i
.PHONY : src/player.i

# target to preprocess a source file
src/player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poker_core.dir/build.make CMakeFiles/poker_core.dir/src/player.cpp.i
.PHONY : src/player.cpp.i

src/player.s: src/player.cpp.s
.PHONY : src/player.s

# target to generate assembly for a file
src/player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poker_core.dir/build.make CMakeFiles/poker_core.dir/src/player.cpp.s
.PHONY : src/player.cpp.s

src/spingo_game.o: src/spingo_game.cpp.o
.PHONY : src/spingo_game.o

# target to build an object file
src/spingo_game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poker_core.dir/build.make CMakeFiles/poker_core.dir/src/spingo_game.cpp.o
.PHONY : src/spingo_game.cpp.o

src/spingo_game.i: src/spingo_game.cpp.i
.PHONY : src/spingo_game.i

# target to preprocess a source file
src/spingo_game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poker_core.dir/build.make CMakeFiles/poker_core.dir/src/spingo_game.cpp.i
.PHONY : src/spingo_game.cpp.i

src/spingo_game.s: src/spingo_game.cpp.s
.PHONY : src/spingo_game.s

# target to generate assembly for a file
src/spingo_game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poker_core.dir/build.make CMakeFiles/poker_core.dir/src/spingo_game.cpp.s
.PHONY : src/spingo_game.cpp.s

src/utils.o: src/utils.cpp.o
.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poker_core.dir/build.make CMakeFiles/poker_core.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poker_core.dir/build.make CMakeFiles/poker_core.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poker_core.dir/build.make CMakeFiles/poker_core.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

tests/test_card.o: tests/test_card.cpp.o
.PHONY : tests/test_card.o

# target to build an object file
tests/test_card.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_card.dir/build.make CMakeFiles/test_card.dir/tests/test_card.cpp.o
.PHONY : tests/test_card.cpp.o

tests/test_card.i: tests/test_card.cpp.i
.PHONY : tests/test_card.i

# target to preprocess a source file
tests/test_card.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_card.dir/build.make CMakeFiles/test_card.dir/tests/test_card.cpp.i
.PHONY : tests/test_card.cpp.i

tests/test_card.s: tests/test_card.cpp.s
.PHONY : tests/test_card.s

# target to generate assembly for a file
tests/test_card.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_card.dir/build.make CMakeFiles/test_card.dir/tests/test_card.cpp.s
.PHONY : tests/test_card.cpp.s

tests/test_game.o: tests/test_game.cpp.o
.PHONY : tests/test_game.o

# target to build an object file
tests/test_game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_game.dir/build.make CMakeFiles/test_game.dir/tests/test_game.cpp.o
.PHONY : tests/test_game.cpp.o

tests/test_game.i: tests/test_game.cpp.i
.PHONY : tests/test_game.i

# target to preprocess a source file
tests/test_game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_game.dir/build.make CMakeFiles/test_game.dir/tests/test_game.cpp.i
.PHONY : tests/test_game.cpp.i

tests/test_game.s: tests/test_game.cpp.s
.PHONY : tests/test_game.s

# target to generate assembly for a file
tests/test_game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_game.dir/build.make CMakeFiles/test_game.dir/tests/test_game.cpp.s
.PHONY : tests/test_game.cpp.s

tests/test_hand_evaluator.o: tests/test_hand_evaluator.cpp.o
.PHONY : tests/test_hand_evaluator.o

# target to build an object file
tests/test_hand_evaluator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_hand_evaluator.dir/build.make CMakeFiles/test_hand_evaluator.dir/tests/test_hand_evaluator.cpp.o
.PHONY : tests/test_hand_evaluator.cpp.o

tests/test_hand_evaluator.i: tests/test_hand_evaluator.cpp.i
.PHONY : tests/test_hand_evaluator.i

# target to preprocess a source file
tests/test_hand_evaluator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_hand_evaluator.dir/build.make CMakeFiles/test_hand_evaluator.dir/tests/test_hand_evaluator.cpp.i
.PHONY : tests/test_hand_evaluator.cpp.i

tests/test_hand_evaluator.s: tests/test_hand_evaluator.cpp.s
.PHONY : tests/test_hand_evaluator.s

# target to generate assembly for a file
tests/test_hand_evaluator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_hand_evaluator.dir/build.make CMakeFiles/test_hand_evaluator.dir/tests/test_hand_evaluator.cpp.s
.PHONY : tests/test_hand_evaluator.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... poker_core"
	@echo "... poker_core_python"
	@echo "... test_card"
	@echo "... test_game"
	@echo "... test_hand_evaluator"
	@echo "... python/poker_module.o"
	@echo "... python/poker_module.i"
	@echo "... python/poker_module.s"
	@echo "... src/action.o"
	@echo "... src/action.i"
	@echo "... src/action.s"
	@echo "... src/card.o"
	@echo "... src/card.i"
	@echo "... src/card.s"
	@echo "... src/deck.o"
	@echo "... src/deck.i"
	@echo "... src/deck.s"
	@echo "... src/game_state.o"
	@echo "... src/game_state.i"
	@echo "... src/game_state.s"
	@echo "... src/hand_evaluator.o"
	@echo "... src/hand_evaluator.i"
	@echo "... src/hand_evaluator.s"
	@echo "... src/player.o"
	@echo "... src/player.i"
	@echo "... src/player.s"
	@echo "... src/spingo_game.o"
	@echo "... src/spingo_game.i"
	@echo "... src/spingo_game.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
	@echo "... tests/test_card.o"
	@echo "... tests/test_card.i"
	@echo "... tests/test_card.s"
	@echo "... tests/test_game.o"
	@echo "... tests/test_game.i"
	@echo "... tests/test_game.s"
	@echo "... tests/test_hand_evaluator.o"
	@echo "... tests/test_hand_evaluator.i"
	@echo "... tests/test_hand_evaluator.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

